services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=user_secret
      - MONGO_URL=mongodb+srv://apurba007:Apurba%40123@learningcluster1.yhtlu.mongodb.net/eMotion-user
      - RABBIT_URL=amqps://kkflqoos:FCLIO17PM9QZLyfDHVhJM3T0otIG30H7@collie.lmq.cloudamqp.com/kkflqoos
      - BASE_URL="http://localhost:8000"
      - WS_SERVER_URL=http://localhost:8080
    restart: unless-stopped

  captain-service:
    build:
      context: ./captain
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=captain_secret
      - MONGO_URL=mongodb+srv://apurba007:Apurba%40123@learningcluster1.yhtlu.mongodb.net/eMotion-captain
      - RABBIT_URL=amqps://kkflqoos:FCLIO17PM9QZLyfDHVhJM3T0otIG30H7@collie.lmq.cloudamqp.com/kkflqoos
      - BASE_URL=http://localhost:8000
      - WS_SERVER_URL=http://localhost:8080
    restart: unless-stopped

  ride-service:
    build:
      context: ./ride
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=production
      - CAPTAIN_SECRET=captain_secret
      - USER_SECRET=user_secret
      - MONGO_URL=mongodb+srv://apurba007:Apurba%40123@learningcluster1.yhtlu.mongodb.net/eMotion-ride
      - RABBIT_URL=amqps://kkflqoos:FCLIO17PM9QZLyfDHVhJM3T0otIG30H7@collie.lmq.cloudamqp.com/kkflqoos
      - BASE_URL=http://localhost:8000
      - WS_SERVER_URL=http://localhost:8080
    restart: unless-stopped

  websocket-server:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      # Add other env vars here
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - captain-service
      - ride-service
      - websocket-server
    restart: unless-stopped
